// <auto-generated />
using System;
using EstoqueService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueService.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    partial class EstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoqueService.Models.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Produtos_Nome");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAtualizacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4170),
                            DataCriacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4168),
                            Descricao = "Notebook Dell Inspiron 15 3000, Intel Core i5, 8GB RAM, SSD 256GB",
                            Nome = "Notebook Dell Inspiron 15",
                            Preco = 2499.99m,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataAtualizacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4177),
                            DataCriacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4176),
                            Descricao = "Mouse sem fio Logitech MX Master 3, sensor de alta precisão",
                            Nome = "Mouse Logitech MX Master 3",
                            Preco = 349.90m,
                            Quantidade = 25
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataAtualizacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4181),
                            DataCriacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4181),
                            Descricao = "Teclado mecânico sem fio Keychron K2, switch Blue, layout ABNT2",
                            Nome = "Teclado Mecânico Keychron K2",
                            Preco = 799.99m,
                            Quantidade = 15
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataAtualizacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4186),
                            DataCriacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4185),
                            Descricao = "Monitor Samsung 27 polegadas, resolução 4K, painel IPS",
                            Nome = "Monitor Samsung 27\" 4K",
                            Preco = 1899.90m,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataAtualizacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4190),
                            DataCriacao = new DateTime(2025, 12, 1, 22, 13, 4, 155, DateTimeKind.Utc).AddTicks(4190),
                            Descricao = "SSD NVMe Kingston NV2 1TB, interface PCIe 4.0",
                            Nome = "SSD Kingston NV2 1TB",
                            Preco = 399.90m,
                            Quantidade = 0
                        });
                });

            modelBuilder.Entity("ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_ProcessedEvents_ProcessedAt");

                    b.HasIndex("EventType", "EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProcessedEvents_Unique");

                    b.ToTable("ProcessedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
